export enum ActionTypes {
    SUBSCRIBE_NEWS_LETTER = 'SUBSCRIBE_NEWS_LETTER',
    SUBSCRIBE_NEWS_LETTER_SUCCEED = 'SUBSCRIBE_NEWS_LETTER_SUCCEED',
    SUBSCRIBE_NEWS_LETTER_FAILED = 'SUBSCRIBE_NEWS_LETTER_FAILED',
    UNSUBSCRIBE_NEWS_LETTER = 'UNSUBSCRIBE_NEWS_LETTER',
    UNSUBSCRIBE_NEWS_LETTER_SUCCEED = 'UNSUBSCRIBE_NEWS_LETTER_SUCCEED',
    UNSUBSCRIBE_NEWS_LETTER_FAILED = 'UNSUBSCRIBE_NEWS_LETTER_FAILED',
}