export enum ActionTypes {
    GET_CATEGORIES = 'GET_CATEGORIES',
    GET_CATEGORIES_SUCCEED = 'GET_CATEGORIES_SUCCEED',
    GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED',
    GET_RECIPES_BY_CATEGORY = 'GET_RECIPES_BY_CATEGORY',
    GET_RECIPES_BY_CATEGORY_SUCCEED = 'GET_RECIPES_BY_CATEGORY_SUCCEED',
    GET_RECIPES_BY_CATEGORY_FAILED = 'GET_RECIPES_BY_CATEGORY_FAILED',
}