export enum ActionTypes {
    INIT_RECIPE_BLOGS = 'INIT_RECIPE_BLOGS',
    SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
    GET_RECIPE_BLOGS = 'GET_RECIPE_BLOGS',
    GET_RECIPE_BLOGS_SUCCEED = 'GET_RECIPE_BLOGS_SUCCEED',
    GET_RECIPE_BLOGS_FAILED = 'GET_RECIPE_BLOGS_FAILED'
}