name: Send Weekly Newsletter

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  send-newsletter:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel API to Send Newsletter
        run: curl -X POST https://cook-craft-web-app.vercel.app/api/news-letter
