name: Send Weekly Newsletter

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  send-newsletter:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel API to Send Newsletter
        run: curl -X POST https://cook-craft-web-app-msmuralis-projects.vercel.app/api/news-letter
